name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install
      - name: Set up iOS Signing Keychain and Certificates
        env:
          IOS_CERTIFICATE_P12: ${{ secrets.IOS_CERTIFICATE_P12 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          # Create a custom keychain
          security create-keychain -p "github-actions" ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p "github-actions" ios-build.keychain

          # Import the certificate (.p12)
          echo $IOS_CERTIFICATE_P12 | base64 --decode > ios_certificate.p12
          security import ios_certificate.p12 -k ios-build.keychain -P $IOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign

          # Set keychain settings
          security set-keychain-settings -t 3600 -u ios-build.keychain
          security list-keychains -d user -s ios-build.keychain

          # Set partition list
          security set-key-partition-list -S apple-tool:,apple: -s -k "github-actions" ios-build.keychain

          # Install the provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $IOS_PROVISIONING_PROFILE | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS IPA
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa