name: Build Android Appbundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Decode base64 keystore from secrets and save it
      - name: Decode and save keystore file
        run: |
          echo "${{ secrets.ANDROID_RELEASE_KEY }}" | base64 -d > upload-key.jks

      # Create key.properties file from secrets
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> key.properties
          echo "storeFile=upload-key.jks" >> key.properties

      # Build the release-signed AAB
      - name: Build Android AppBundle
        run: flutter build appbundle

      # Archive the output bundle
      - name: Archive AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
